### ISSUE TITLE
Website Link

### ISSUE THREAD

**Issue by KarlDominic** [rstropek-teaching/form-validation-quiz-4bhif-KarlDominic#1]
http://jumper0907.bplaced.net/

**Comment by rstropek** [comment]
Thank you for the link. The solution is nearly correct. The *submit* button is not enabled/disabled properly in case of invalid data in the form.

One other thing: **Never** put source code in the *dist* folder. It only receives the compiled code. You should be able to delete the *dist* folder without losing code.

Greetings,
Rainer Stropek.
